### ISSUE TITLE
API not working?

### ISSUE THREAD

**Issue by derekshull** [mavenlink/mavenlink_php_api#7]
Is this API not working anymore?  I'm using curl and seeing results but whenever I try using this API I get no results or errors.  I'm assuming this project is not usable anymore?

**Comment by cantino** [comment]
Hey @derekshull, we haven't changed our API, so I'm surprised that this isn't working for you.  We'll investigate.

**Comment by derekshull** [comment]
I figured it out.  I'm going to make a change and do a pull request.

**Comment by cantino** [comment]
Awesome, thank you!
